spring.application.name=smart-campus-api
# MongoDB: Spring Boot 4 uses spring.mongodb.*
spring.mongodb.uri=mongodb+srv://smartcampus_admin:VzHFmhahTOFXa8dK@cluster0.vd0oqe5.mongodb.net/smart_campus?authSource=admin&retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://smartcampus_admin:VzHFmhahTOFXa8dK@cluster0.vd0oqe5.mongodb.net/smart_campus?authSource=admin&retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.database=smart_campus
spring.data.mongodb.auto-index-creation=true

server.port=8081
server.max-http-header-size=1MB
server.max-http-request-header-size=1MB
server.max-http-response-header-size=1MB
logging.level.org.springframework.data.mongodb=DEBUG
spring.profiles.active=local

logging.file.name=smart-campus-backend.log
logging.file.path=.

# JWT Configuration
app.jwt.secret=9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
app.jwt.expiration=86400000

logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web.client.RestTemplate=TRACE

# OAuth2 Frontend Redirect Callback
app.oauth2.redirectUri=http://localhost:5173/auth/callback

# Google OAuth2 Client Configuration placeholders (put real ones in application-local.properties)
spring.security.oauth2.client.registration.google.client-id=803092642823-bn2f4vkqmagtjh4etogcff6q6b3q0h1d.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=danirudevanmith2003@gmail.com
spring.mail.password=mlfvcdemgczupfiu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true